name: Release Helm Chart

on:
  push:
    branches:
      - main
      - refactor/Helm_chart_publishing
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Release Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.3

      - name: Install Chart Releaser
        run: |
          curl -sSL https://github.com/helm/chart-releaser/releases/latest/download/chart-releaser-linux-amd64.tar.gz | tar xz
          sudo mv cr /usr/local/bin/

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release